### ISSUE TITLE
ROS Location Window Issue

### ISSUE THREAD

**Issue by Daniel-Gill** [Railway-Op-Sim/ROSTimetableEditor#1]
**Image of issue:**
![image](https://user-images.githubusercontent.com/56364196/74869089-41390880-534f-11ea-8398-04610e5322e7.png)

**OS specification:**
Windows 7 Ultimate Service Pack 1

**Comment by AlbertBall** [comment]
Hi Daniel,

For now you need to type in the name of the railway executable, normally
railway.exe. I think in time the name of executables will appear in the
drop down box.

Albert

**Comment by Daniel-Gill** [comment]
Hi Albert,

This is what I have been doing to fix this problem in the time being. I believe that @artemis-beta wanted this posting for evidence so that the issue can be fixed in the future. :)

Daniel

**Comment by AlbertBall** [comment]
Hi Daniel,

Yes he did. I only realised that after reading more of the Discord posts. I
should have read those first!

Cheers,

Albert

**Comment by zarethrex** [comment]
I have added a couple of things but as this issue does not occur on Mac and there is no obvious reason fixing this is tricky

**Comment by zarethrex** [comment]
Possible fix in cc0391d7168008ba10ac295daa31ac6f4223dba1

Issue was I comma separated the types as opposed to using a space

**Comment by Daniel-Gill** [comment]
![image](https://user-images.githubusercontent.com/56364196/75582398-628ea880-5a63-11ea-9887-a506fdcf73de.png)

Appears to be fixed in release v0.1.9-alpha.

**Comment by zarethrex** [comment]
Great to hear @Daniel-Gill, I will mark this as closed. Reopen if it becomes an issue again in future.
