### ISSUE TITLE
Liverpool Heavy Traffic timetable opening

### ISSUE THREAD

**Issue by AlbertBall** [Railway-Op-Sim/ROSTimetableEditor#10]
Opens with service ref 2D01 shown in box with parent 2D00, whereas the listing is for 2H01 with parent 2H00
![TTEditor](https://user-images.githubusercontent.com/12687089/75091397-9b5ee700-5564-11ea-9b43-5b70c383f5b9.jpg)

**Comment by zarethrex** [comment]
Hi @AlbertBall thanks for this, thankfully this is a minor issue as once you click an entry it updates. This is just a case of playing around with the default opening display which I shall play around with. Probably a missing `update()` somewhere.

**Comment by zarethrex** [comment]
Ok I see the issue, currently the `_current_service_selection` variable is set to be the last entry `end()` in the list. But this is not the one being shown.

Trying a cheeky fix where I read in the currently displayed service from the widgets themselves and feed that back in.

**Comment by zarethrex** [comment]
Scratch that, was just a one line fix!

Fixed in 20ce511becd6d8f2594e6871169e57e37471cb9d
