### ISSUE TITLE
Pass and join times

### ISSUE THREAD

**Issue by AlbertBall** [Railway-Op-Sim/ROSTimetableEditor#11]
On loading a timetable service with pass times or join times, the time box is blank.  The service shown is 1A23 (Birmingham), which is joined by 1A21 at 07:11, but the join event and time aren't shown. Also the pass times aren't shown.

![TTEditor2](https://user-images.githubusercontent.com/12687089/75091478-a0706600-5565-11ea-8e03-683eddd55831.jpg)

**Comment by Daniel-Gill** [comment]
Hi,

I noticed a similar issue with the Liverpool ones when a service finishes and forms a new one. If I remember correctly, when you double click on one, the blank time appeared to be 00:00.

Is this necessary for programming a finish and form new service? Little confused on this. :(

Dan

**Comment by zarethrex** [comment]
@AlbertBall also curious about that "NULL" "NULL" that should not be there!

**Comment by zarethrex** [comment]
Fixed in 66ef3765e93d3e18261e8c67f30b607f57f75cb1
