### ISSUE TITLE
Location List items duplicated.

### ISSUE THREAD

**Issue by Daniel-Gill** [Railway-Op-Sim/ROSTimetableEditor#3]
The drop-down box for selecting a location appears to continue to repeat roughly 12 times.

This happens on the Liverpool Loop route, and I have not checked this bug on other routes.

![image](https://user-images.githubusercontent.com/56364196/74989391-1f678080-5438-11ea-95e7-81fa41ea628f.png)

![image](https://user-images.githubusercontent.com/56364196/74989410-2a221580-5438-11ea-881f-bbc17fafd06c.png)

**Comment by Daniel-Gill** [comment]
Just to confirm, this does also happen on the IslandLine route, except with 4 repetitions.

**Comment by zarethrex** [comment]
This one is very odd because I do not have that issue on Mac
<img width="1027" alt="Screenshot 2020-02-21 at 17 06 58" src="https://user-images.githubusercontent.com/15262250/75055274-9f3f2a80-54cc-11ea-8271-a7d8a120d357.png">

**Comment by zarethrex** [comment]
Fixed in 72f05cd838ed2dbcc7714f18ea81be21d1a7ac38
