### ISSUE TITLE
Arrival but no departure

### ISSUE THREAD

**Issue by AlbertBall** [Railway-Op-Sim/ROSTimetableEditor#34]
Unclear how to enter an arrival time only, for a service followed by a change of direction then finishing to form a new service - documentation may clarify

**Comment by Daniel-Gill** [comment]
@AlbertBall As far as I can see, you have to enter a departure time, then select `Change Direction` and assuming the `Finish and Form New Service` is selected it seems to save fine. I'm sure @artemis-beta can confirm though.

![image](https://user-images.githubusercontent.com/56364196/126903416-b10e9390-bf14-4d62-a27d-377a26071c1c.png)

**Comment by AlbertBall** [comment]
Thanks, that worked OK.  I'm hampered by thinking in terms of the existing editor when this works quite differently.
