### ISSUE TITLE
Program not saving edited information.

### ISSUE THREAD

**Issue by Daniel-Gill** [Railway-Op-Sim/ROSTimetableEditor#5]
![Issues](https://user-images.githubusercontent.com/56364196/74991227-44aabd80-543d-11ea-90b5-ae5700099908.gif)

Please see gif above.

I am unticking 'Station/Siding Start' and setting some information for the repeats, however, this information is not saved to the service when the 'Insert/Edit' button.

This issue also occurs when the service is initially inserted, making it not possible to make a repeat.

Please let me know if I am doing something wrong.

Thanks,
Daniel

**Comment by zarethrex** [comment]
Taking your example, this issue has now been fixed. The problem was due to the fact in early development I thought normal services could not be repeated which of course is not true. I have made it global now. bb1488d2440058204a2cfa7179609637cc3dae3b
