### ISSUE TITLE
Route display cuts of at spaces.

### ISSUE THREAD

**Issue by Daniel-Gill** [Railway-Op-Sim/ROSTimetableEditor#8]
![image](https://user-images.githubusercontent.com/56364196/75060790-65275600-54d7-11ea-993f-9b5c0a326af0.png)

I'm not sure that this will be causing any issues, but making sure it does not cut off at spaces will make it look nicer I think.

Thanks,
Daniel

**Comment by zarethrex** [comment]
Hi Daniel this is pretty minor point and cannot be helped, I can lengthen the text box, but the length is limited still of course by the window size

**Comment by zarethrex** [comment]
Boxes lengthened to max in 4b5b402267b91a0af4951dbd577b1a43af18eccf
